<form action="" method="post">
<fieldset>
    <label for="email">Enter your email:</label>
<input type="email" id="email" name="email">
</fieldset>

<fieldset>
    <label for="pass">Password:</label>
    <input type="password" id="pass" name="password">
</fieldset>

<fieldset>
    <input type="hidden" id="postId" name="formName" value="34657">
</fieldset>

<input type="submit" value="Se connecter">