<form action="" method="post">
<fieldset>
    <label for="name">Prénom:</label>

<input type="text" id="name" name="name" required
       minlength="4"  size="10">

</fieldset>
<fieldset>
     <label for="name">Nom:</label>

<input type="text" id="name" name="name" required
       minlength="4" size="10">
</fieldset>
<fieldset>
     <label for="email">Enter your email:</label>
    <input type="email" id="email" name="email">
</fieldset>
<fieldset>
    <label for="pass">Password:</label>
    <input type="password" id="pass" name="password">
</fieldset>
<fieldset>
     <label for="pass">Confirm Password:</label>
    <input type="password" id="pass" name="password">
</fieldset>

<fieldset>
    <input type="hidden" id="postId" name="formName" value="34657">
</fieldset>