<!-- ça manque d'action ce truc --><!-- ça manque toujours cruellement d'action -->
<form action="index.php?route=creer-un-compte" method="post">
<fieldset>
    <label for="firstName">Prénom:</label>

<input type="text" id="firstName" name="firstName" required
       minlength="4"  size="10">

</fieldset>
<fieldset>
     <label for="lastName">Nom:</label>

<input type="text" id="lastName" name="lastName" required
       minlength="4" size="10">
</fieldset>
<fieldset>
     <label for="email">Enter your email:</label>
    <input type="email" id="email" name="email">
</fieldset>
<fieldset>
    <label for="pass">Password:</label>
    <input type="password" id="pass" name="password">
</fieldset>
<fieldset>
     <label for="pass">Confirm Password:</label>
    <input type="password" id="pass" name="password">
</fieldset>

<fieldset>
    <input type="hidden" id="postId" name="formName" value="register">
</fieldset>

<input type="submit" value="Envoyez">
<!-- ajouter un submit -->